services:
  # postgres:
  #   image: postgres:15
  #   container_name: ps-be-person-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: person
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: ps-be-person-localstack
    environment:
      - SERVICES=sns,sqs
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - localstack-data:/tmp/localstack

volumes:
  # pgdata:
  localstack-data:
